### ISSUE TITLE
Larger board?

### ISSUE THREAD

**Issue by aletote** [evg-tyurin/alpha-nagibator#3]
Is there anyway that this or any other game could work with a say 80x80 board? I want to use it on my own game but the board will be that big and when I try using this size with Checkers, TicTacToe, Othello, Connect4 or Gobang I run out of memory. I see CNN networks trained all the time with pictures with higher resolution than this, so... what am I missing?

**Comment by evg-tyurin** [comment]
Memory consumption in CNN for image processing and alpha-zero algorithms are different. Huge amount of memory consumed at self-play stage where the MCTS trees are growing in memory. The bigger is your board the longer is every game (every MCTS simulation on every move) and the larger amount of memory required for each iteration. The same is true on evaluation stage.

Total memory consumption also depends on a number of parallel processes you use for training. 

You can monitor your memory consumption by changing training parameters starting from minimal. You can start from single-process training, number of MCTS simulation = 10 or 20, number of episodes = 2 and then watch how many memory would consume on each stage of iteration. Then you can enlarge training parameters as well as enlarge computer's RAM.

**Comment by aletote** [comment]
I get the other parameters, but do I start from single-process training?

**Comment by evg-tyurin** [comment]
If you use checkers_main.py to run all stages of an iteration then see at the top of the file. Comment/Uncomment appropriate lines of code marked either "single-threaded self-play" or "multi-threaded self-play". This affects self-play phase. Then look in Coach.compare_networks() and set mcts_threads=1. This affects evaluate phase.

**Comment by aletote** [comment]
Thanks for your advice, I tried lowering the parameters and it works. I'm testing it with Connect4 on 30x30 and it runs fine. But when I go anything higher I get this error:

File "/content/alpha-zero-general/MCTS.py", line 114, in search
    next_s, next_player = self.game.getNextState(canonicalBoard, 1, a)
  File "/content/alpha-zero-general/connect4/Connect4Game.py", line 30, in getNextState
    b.add_stone(action, player)
  File "/content/alpha-zero-general/connect4/Connect4Logic.py", line 32, in add_stone
    raise ValueError("Can't play column %s on board %s" % (column, self))
ValueError: Can't play column 17 on board [[-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 ...
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-1. -0. -0. ... -0. -0. -0.]]

Do you have any idea what could cause it?

PS: I'm using Connect4 because it has a reduced action space given by the number of columns like the game I need to make. 30 columns would work for my game, but I need 100 rows.

If you wanna test it this are the parameters I changed:
    'numIters': 100000,
    'numEps': 2,
    'numMCTSSims': 5,
    'arenaCompare': 2,

    'batch_size': 128,
    'num_channels': 128,

s_fc1 = Dropout(Relu(BatchNormalization(Dense(h_conv4_flat, 128), axis=1, training=self.isTraining)), rate=self.dropout)  
s_fc2 = Dropout(Relu(BatchNormalization(Dense(s_fc1, 128), axis=1, training=self.isTraining)), rate=self.dropout)

**Comment by evg-tyurin** [comment]
The error looks like Connect4 specific error. I'd propose to post the issue into the repo which hosts this game implementation.
